### ISSUE TITLE
RenameStatement doesn't build()

### ISSUE THREAD

**Issue by travisghansen** [phpmyadmin/sql-parser#201]
When trying to convert a RenameStatement to a string representation the result is empty.

**Comment by devenbansod** [comment]
Thanks for the report @travisghansen . Can you share the query that you're trying to build?

We do have some tests for building the `REPLACE` statement which seem to pass (ref: https://github.com/phpmyadmin/sql-parser/blob/master/tests/Builder/ReplaceStatementTest.php). We might be missing a special query though. That's why your example might help.

**Comment by travisghansen** [comment]
```
RENAME TABLE `tech_schedule` TO `tech_schedule_old`
```
