### ISSUE TITLE
Uncaught TypeError: str_repeat() expects parameter 2 to be integery, null given

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/sql-parser#272]
Highlighting a query causes an error about str_repeat with current master.

```cat case.sql | ./bin/highlight-query

Fatal error: Uncaught TypeError: str_repeat() expects parameter 2 to be integer, null given in /Users/isaacbennetch/Documents/svn/pma/sql-parser/src/Utils/Formatter.php:497
Stack trace:
#0 /Users/isaacbennetch/Documents/svn/pma/sql-parser/src/Utils/Formatter.php(497): str_repeat('    ', NULL)
#1 /Users/isaacbennetch/Documents/svn/pma/sql-parser/src/Utils/Formatter.php(671): PhpMyAdmin\SqlParser\Utils\Formatter->formatList(Object(PhpMyAdmin\SqlParser\TokensList))
#2 /Users/isaacbennetch/Documents/svn/pma/sql-parser/src/Utils/CLI.php(89): PhpMyAdmin\SqlParser\Utils\Formatter::format('select\ncase whe...', Array)
#3 /Users/isaacbennetch/Documents/svn/pma/sql-parser/bin/highlight-query(30): PhpMyAdmin\SqlParser\Utils\CLI->runHighlight()
#4 {main}
  thrown in /Users/isaacbennetch/Documents/svn/pma/sql-parser/src/Utils/Formatter.php on line 497
```

This is the content of `case.sql`

```select
case when count(id)>0
  then 'Yes'
  else 'No'
end
from products where 1;
```

This works correctly with the QA branch, but git bisect doesn't help me. I've tested with both PHP 7.1.23 and PHP 7.4.0.

**Comment by mauriciofauth** [comment]
The commit 1a99634c6c7251af1bb0cea8e3ab5d7a88427d91 fixes the uncaught TypeError, but I don't think it is a proper fix.

This issue started to happen because we [enabled](https://github.com/phpmyadmin/sql-parser/commit/17da8a34b81442524a8e01fead7b5968fa1cc39d) the PHP strict mode. Before `null` was being implicit converted to `int`.
Looks like _sql-parser_ only expects an END after a BEGIN. It doesn't handle the [CASE statement](https://dev.mysql.com/doc/refman/8.0/en/case.html) well enough.

`array_pop()` returns `null` if `$blocksIndentation` [is empty or is not an array](https://www.php.net/manual/en/function.array-pop.php#refsect1-function.array-pop-returnvalues).

https://github.com/phpmyadmin/sql-parser/blob/1a99634c6c7251af1bb0cea8e3ab5d7a88427d91/src/Utils/Formatter.php#L441-L449

I think we should close this issue and open a new one related to the CASE statement issue. What do you think @ibennetch ?

**Comment by ibennetch** [comment]
I tend to agree; it seems that your commit suppresses the actual error but we should still make a new issue to address the underlying shortcomings with CASE statements.

Good research and conclusion.

**Comment by mauriciofauth** [comment]
Thank you. No problem, I can open the issue.

**Comment by williamdes** [comment]
what about QA branch?

**Comment by mauriciofauth** [comment]
This TypeError only affects `master`.

**Comment by williamdes** [comment]
Okay, because of the php version?

**Comment by mauriciofauth** [comment]
No, because of `declare(strict_types=1);`.
