### ISSUE TITLE
Parsing comments issues 

### ISSUE THREAD

**Issue by kefiGhazi** [phpmyadmin/sql-parser#285]
Hi,
When I parse this valid SQL statement:
`SELECT */* comment */ FROM table_name` 
the parser divides `*/*` into two tokens: 

- 1st token with `*/` in value and type TYPE_COMMENT
- 2nd token with `*`  in value and type TYPE_OPERATOR

The expected behavior would be:
- 1st token with `*` in value and type TYPE_OPERATOR
- 2nd token with `/*`  in value and type TYPE_COMMENT

Do you agree on that, and if yes, would you like help on providing a PR?
Thanks a lot

**Comment by ibennetch** [comment]
Hello,

Your report looks correct to me, I agree that this looks like a bug.

A pull request would be welcome.

Thank you!

**Comment by williamdes** [comment]
I agree, please target QA branch if possible

**Comment by niconoe-** [comment]
Hi, I'm sorry, I started the development from master and I didn't see your message.
When I wanted to propose my PR to QA instead of master, it came with 44 commits while I only did 1.

If you really need this in QA, could you help me to rebase it correctly? I'm not very fluent in this kind of manipulation.

Thanks a lot.
Regards,

**Comment by williamdes** [comment]
Hi @niconoe-  
I think you can finish the work on master branch and I will manage the rebasing work when I merge the PR

Basically I will hard reset your branch to QA and cherry-pick each commit and the force push.

Thank you
