### ISSUE TITLE
Valid ALTER USER statement throws validation error "unrecognized alter operation"

### ISSUE THREAD

**Issue by pcgeek86** [phpmyadmin/sql-parser#342]
### Describe the bug

When writing an `ALTER USER` statement in phpMyAdmin, a validation error is thrown, even though the query executes successfully.

### To Reproduce

Put the following query into the phpMyAdmin SQL query editor.

```
ALTER USER trevor REQUIRE NONE;
```

### Expected behavior

Query should not show any validation errors in the phpMyAdmin SQL editor.

### Screenshots

![image](https://user-images.githubusercontent.com/466713/129116728-1950cd1b-7d2f-4757-86e1-38293477bc4e.png)
![image](https://user-images.githubusercontent.com/466713/129116827-5d8d881e-dff0-4d71-89d4-e7edb6725e97.png)

### Server configuration

- Operating system: Windows 10 w/ Docker Desktop
- Web server: Apache
- Database version: MySQL 8.0.26
- PHP version: 
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: Firefox 91
- Operating system: Windows 10

**Comment by iifawzi** [comment]
In order for to fix this issue, I think we would need to create a `USER_OPTIONS` similar to https://github.com/phpmyadmin/sql-parser/blob/b18edd6d1e6766bbc806f29bd1a553a7ef9ac753/src/Components/AlterOperation.php#L30

to be used here: 
https://github.com/phpmyadmin/sql-parser/blob/b18edd6d1e6766bbc806f29bd1a553a7ef9ac753/src/Statements/AlterStatement.php#L112-L121

otherwise; this will always be the error
https://github.com/phpmyadmin/sql-parser/blob/b18edd6d1e6766bbc806f29bd1a553a7ef9ac753/src/Components/AlterOperation.php#L311-L313

I don't really know what's the full list of user options, if you could help me @williamdes I might be able to work on a fix.

**Comment by williamdes** [comment]
@iifawzi you figured out before I finished writing my message here ^^

I was about to give you more details about options but here are the links:
- https://dev.mysql.com/doc/refman/8.0/en/alter-user.html
- https://mariadb.com/kb/en/alter-user/
