### ISSUE TITLE
Example usage and wiki

### ISSUE THREAD

**Issue by Azuka** [phpmyadmin/sql-parser#42]
Hi.

Have you considered adding documentation and use cases for this library? This looks like the most actively developed php sql parser.

Does it support reconstituting an sql statement from parse results, e.g. for anonymization before logging?

**Comment by ibennetch** [comment]
Hi and thanks for your interest. Yes, creating documentation is a goal, but since this library was only recently abstracted away from the core of phpMyAdmin, it's obviously taking some time to come up with. We'll definitely put some effort in to this and hope you are able to use the sql-parser library!

**Comment by ibennetch** [comment]
About the anonymization before logging, you probably should open a separate issue about that. I don't know the answer but don't want your question to get lost in this documentation discussion.

**Comment by nijel** [comment]
I've added really basic examples to README, but we should definitely have better docs.

**Comment by Azuka** [comment]
Thanks for the quick response guys. 

I used regex for my needs, but seeing there's a build method, it should be easy to iterate (or recurse) and modify the values.

**Comment by alok-sin** [comment]
Does it support something like:
`select * FROM (select Pop FROM MyTable) p join tadaa t where p.x=t.y order by p.pop`

**Comment by nijel** [comment]
It currently seems to fail on this. Please open separate issue for this.
