### ISSUE TITLE
Unable to parse table names that start with "e1"

### ISSUE THREAD

**Issue by sergio-paternoster** [phpmyadmin/sql-parser#578]
Not sure if this is a bug of just a table name with reserved keywords. If the name of my table starts with "e1" the parser is unable to recognize it. It works with any other table name that doesn't start with "e1". Here is my code (SqlParser v.5.10, php version 8.2.16 CLI):

```php
use PhpMyAdmin\SqlParser\Parser         as Parser;

$query = "LOAD DATA LOCAL INFILE '/home/user/myloadfile.csv' 
          IGNORE INTO TABLE erp.e1_table
          FIELDS TERMINATED BY '\t'
          LINES TERMINATED BY '\n'
          IGNORE 0 LINES;";

$parser                                 = new Parser($query);
echo "\n file:   ".$parser->statements[0]->file_name->file;
echo "\n schema: ".$parser->statements[0]->table->database;
echo "\n table:  ".$parser->statements[0]->table->table;
```

This is the actual output:

```
 file:   /home/user/myloadfile.csv
 schema:
 table:  erp
```

Expected output:
```
 file:   /home/user/myloadfile.csv
 schema: erp
 table:  e1_table
```

**Comment by sergio-paternoster** [comment]
Actually the same problem happens with any table name that starts with "e" followed by a number.

**Comment by williamdes** [comment]
Thank you @sergio-paternoster for reporting this

@niconoe- did you encounter this bug ?

**Comment by niconoe-** [comment]
> Thank you @sergio-paternoster for reporting this
> 
> @niconoe- did you encounter this bug ?

Never heard about it, but based on what has been said here, my thoughts are that the lexer fails to understand "e[0-9]+" as a string here, but instead as an integer (10^n).
I'll try to investigate about it.

**Comment by niconoe-** [comment]
Sorry for double posting here, but this is no longer about testing the bug, but rather about the explaination of the bug.

The lexer is trying all of these methods and stops as soon as the method matches with a "lexable" token:
* parseDelimiter
* parseWhitespace
* parseNumber
* parseComment
* parseOperator
* parseBool
* parseString
* parseSymbol
* parseKeyword
* parseLabel
* parseUnknown

With the string "erp.my_table", the lexer detects that:
* "erp" is matched thanks to `parseUnknown`
* "." is matched thanks to `parseOperator`
* "my_table" is matched thanks to `parseUnknown`

But, with the string "erp.e1_table", the lexer detects that:
* "erp" is matched thanks to `parseUnknown`
* ".e1" is matched thanks to **`parseNumber`** !!
* "_table" is matched thanks to `parseUnknown`

Why that ? Because `parseNumber` is executed before `parseOperator`, and the string of characters `.e1` is wrongly detected as a number because of scientific notation. 

@williamdes it may have an impact, but looking at the `parseNumber` method in the Lexer, we should review the steps in order to stop considering something that starts with a dot "." can be followed by the "e" or "E" char (if we actually want to parse a number).
What do you think about?

**Comment by williamdes** [comment]
> Why that ? Because parseNumber is executed before parseOperator, and the string of characters .e1 is wrongly detected as a number because of scientific notation.

> @williamdes it may have an impact, but looking at the parseNumber method in the Lexer, we should review the steps in order to stop considering something that starts with a dot "." can be followed by the "e" or "E" char (if we actually want to parse a number).
What do you think about?


If I understand this correctly by reading the code of your PR you change the step order to avoid this e/E detection ?

**Comment by niconoe-** [comment]
> If I understand this correctly by reading the code of your PR you change the step order to avoid this e/E detection ?

Yes, but only on a certain context.

When a string **starts** with ".", it must be detected as a number if it is followed by a digit. But when a string **contains** a ".", it must be detected as a number if it is followed by a digit or "e"/"E" for scientific notation. This difference wasn't taken into account in the lexer.

I hope this is understandable through my comments and my PR :smile:

**Comment by niconoe-** [comment]
@sergio-paternoster I think you can avoid the parsing error by using quote-identifiers around your table names.
```php
use PhpMyAdmin\SqlParser\Parser         as Parser;

$query = "LOAD DATA LOCAL INFILE '/home/user/myloadfile.csv' 
          IGNORE INTO TABLE `erp`.`e1_table`
          FIELDS TERMINATED BY '\t'
          LINES TERMINATED BY '\n'
          IGNORE 0 LINES;";
```

This should unlock the situation for you waiting for a patch version integrating #579 is released.
