### ISSUE TITLE
Allow two indexes on same column

### ISSUE THREAD

**Issue by IshaniCP** [phpmyadmin/sql-parser#65]
Allow more than one index on the same column or column list. Since more indexes direct for less efficiency, it will be better to avoid creating more than one indexes on same column list.

**Comment by devenbansod** [comment]
Sorry, but I am unable to understand how SQL parser or phpMyAdmin is not allowing you to do so ? Could you provide some explanation ? 

Only if you define same index (same type, same columns etc.) twice with a different name, phpMyAdmin would still allow you to do so, but give a notice saying that 'both these indexes seem to be equal and one of them can be removed.'

**Comment by IshaniCP** [comment]
I kindly apologise for the late reply and unclearness of the question I
asked. Since I am a very beginner to open source contribution, highly
appreciate your guidance ahead.
What I wanted to say was 'PhpMyAdmin currently allow to have two or more
indexes on the same column list and it is a disadvantage for the
efficiency'. I would like to suggest to inform users using a popup message
rather than displaying it in the fieldset 'index_info' as it is hidden
and user have to extract index fieldset to view it.

Thank you.

**Comment by devenbansod** [comment]
Hi @IshaniCP , Thank you for your suggestion. 
First of all I feel this issue is more related to [phpMyAdmin](https://github.com/phpmyadmin/phpmyadmin) itself than the SQL parser, so I suggest you can open a new issue there and continue the discussion there and add a link to *this* issue in the description so that the discussion can be continued there. (I am closing this from here).

Also as you might have noticed, if two or more indices have exactly same characteristics (like same type of index, same column list etc.), we currently *do* provide a *notice* displayed inside the `Indexes` slider on Table structure page. 
About the point that it being hidden from user, we already provide a config option `$cfg['InitialSliderState'] = 'open'` to allow the user to see the sliders open by-default, so that he/she can see these notices directly.
